default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: knajping_development

test:
  <<: *default
  database: knajping_test

production:
  primary: &primary_production
    <<: *default
    database: knajping_production
    username: knajping
    password: <%= ENV["KNAJPING_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: knajping_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: knajping_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: knajping_production_cable
    migrations_paths: db/cable_migrate
